### PR TITLE
Add GIF showcasing the application to the readme

### LINKED ISSUE #2: GIF
Add A  GIF

### PR DESCRIPTION
**Pull request by keevan**
Closes #2 

Feel free to suggest a different one

### CODE REVIEW

**Comment by DaffyTheDuck** [comment]
Hey, You Are Supposed To Add A GIF Of The Working Application :D

**Comment by keevan** [comment]
> Hey, You Are Supposed To Add A GIF Of The Working Application :D

Haha, probably could have made it clearer in the issue. All good I'll make the change :P

**Comment by DaffyTheDuck** [comment]
Didn't think someone will actually ask to do it XD

**Comment by DaffyTheDuck** [comment]
Nice 👍🏼

**Pull request merged**
